---
steps:
  - id: 'fmt-validate'
    name: 'hashicorp/terraform:0.14.8'
    dir: 'terraform/iac-pipelines-with-terraform-and-cloud-build/workloads'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          set -e
          for folder in $(ls .); do

            echo "+-------------------------------------------+"
            echo "Fmt/Validate state ${folder} "
            echo "+-------------------------------------------+"

            cd $folder

            terraform fmt -recursive -check -diff .

            terraform init -backend=false
            terraform validate .
            cd -
          done

  - id: 'tflint'
    name: 'wata727/tflint'
    dir: 'terraform/iac-pipelines-with-terraform-and-cloud-build/workloads'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          set -e
          for folder in $(ls .); do

            echo "+-------------------------------------------+"
            echo "tflint state ${folder} "
            echo "+-------------------------------------------+"

            cd $folder
            tflint .
            cd -
          done
  - id: 'terraform-init-plan'
    waitFor:
      - 'fmt-validate'
      - 'tflint'
    name: 'hashicorp/terraform:0.14.8'
    dir: 'terraform/iac-pipelines-with-terraform-and-cloud-build/workloads'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          set -e
          for folder in $(ls .); do
            echo "+-------------------------------------------+"
            echo "Planning state ${folder} "
            echo "+-------------------------------------------+"
            cd $folder
            terraform init
            terraform plan
            cd -
          done
